FROM python:3.11-slim-bookworm

RUN mkdir -p /app
WORKDIR /app

COPY requirements.lock /app/
RUN pip install --no-cache-dir -r requirements.lock

COPY langc /app/langc
COPY docker_entrypoint.py /app/

EXPOSE 8080

CMD ["python", "docker_entrypoint.py"]
